### ISSUE TITLE
ERROR!!! Problem in decrypting application request 

### ISSUE THREAD

**Issue by kesamani** [avinash-gotluru/cc_avenue#11]
![WhatsApp Image 2023-04-06 at 5 49 55 PM](https://user-images.githubusercontent.com/56714879/230380496-61b59c8f-295a-477a-a965-f96b7c288201.jpeg)
image showing problem in decrypting application request
but I put exactly as what described on Package Plz help
how to decrypt request please guide me

**Comment by avinash-gotluru** [comment]
@kesamani did you check with test credentials?

**Comment by kesamani** [comment]
yes i used test  credentials

**Comment by avinash-gotluru** [comment]
Can you please share this code snippet? 

```
CcAvenue.cCAvenueInit(
        transUrl: '',
        accessCode: '',
        amount: '',
        cancelUrl: '',
        currencyType: '',
        merchantId: '',
        orderId: '',
        redirectUrl: '',
        rsaKeyUrl: ''
      );
```

**Comment by kesamani** [comment]
CcAvenue.cCAvenueInit(
          transUrl: 'https://test.ccavenue.com/transaction/initTrans',
          //transUrl: 'https://secure.ccavenue.com/transaction.do?command=initiateTransaction',
          accessCode: '<access_code>',
      
          amount: '1',
          cancelUrl: 'http://122.182.6.216/merchant/ccavResponseHandler.jsp',
          currencyType: 'INR',
          merchantId: '<merchant_id>',
        
          orderId: '519',
          redirectUrl: 'http://122.182.6.216/merchant/ccavResponseHandler.jsp',
          rsaKeyUrl: 'https://secure.ccavenue.com/transaction/jsp/GetRSA.jsp
      );

**Comment by avinash-gotluru** [comment]
is your merchantId is valid ?

**Comment by kesamani** [comment]
hey its working now when i used production transUrl instead of test transUrl .
thanks for responding...........
