### ISSUE TITLE
I am getting error caller ip not registerd ,merchant not found

### ISSUE THREAD

**Issue by zaheermirmir** [avinash-gotluru/cc_avenue#13]
caller ip not registerd ,merchant not fount

**Comment by avinash-gotluru** [comment]
@zaheermirmir your website or IP has not been whitelisted by the CCAvenue Team. Please try to reach them.

**Comment by avinash-gotluru** [comment]
This is not an issue related to the Package

**Comment by zaheermirmir** [comment]
> @zaheermirmir your website or IP has not been whitelisted by the CCAvenue Team. Please try to reach them.

i have already whitelist my website ip adress but in this package where can i use my web ip ????
