### ISSUE TITLE
How to know if user has made payment successfully?

### ISSUE THREAD

**Issue by Arunshaik2001** [avinash-gotluru/cc_avenue#15]
There is no callback for payment success and failure. how to know a payment is successful?

**Comment by avinash-gotluru** [comment]
@Arunshaik2001 These are hosted Pages.  Which comes out of PCI compliance. Please refer CC_Avenue Office Docs for More Info

**Comment by Arunshaik2001** [comment]
Ok thank u, @avinash-gotluru can i use the redirect and cancel urls provided by the package in production environment.

**Comment by avinash-gotluru** [comment]
Those are test details we suggest not to use them.
