### ISSUE TITLE
how to solve this error?

### ISSUE THREAD

**Issue by positiveabhii** [avinash-gotluru/cc_avenue#18]
PlatformException(error, Unable to find explicit activity class {com.shoppier.discountlo/com.avinash.gotluru.cc_avenue.Framework.WebViewActivity}; have you declared this activity in your AndroidManifest.xml, or does your intent not match its declared <intent-filter>?, null, android.content.ActivityNotFoundException: Unable to find explicit activity class {com.shoppier.discountlo/com.avinash.gotluru.cc_avenue.Framework.WebViewActivity}; have you declared this activity in your AndroidManifest.xml, or does your intent not match its declared <intent-filter>?

**Comment by avinash-gotluru** [comment]
Please add these lines in the manifest file

``` <activity android:name="com.avinash.gotluru.cc_avenue.CcAvenuePlugin" android:theme="@style/Theme.AppCompat.NoActionBar"/>
   <activity android:name="com.avinash.gotluru.cc_avenue.Framework.StatusActivity" android:theme="@style/Theme.AppCompat.NoActionBar"/>
   <activity android:name="com.avinash.gotluru.cc_avenue.Framework.WebViewActivity" android:theme="@style/Theme.AppCompat.NoActionBar"/>

**Comment by avinash-gotluru** [comment]
@abhijain1705 Please let us know did it worked for you..

**Comment by positiveabhii** [comment]
not really we spoke to ccavenue and they said they have closed their android sdk for flutter

no support
