### ISSUE TITLE
Null safety is not supported

### ISSUE THREAD

**Issue by mhdJasir** [avinash-gotluru/cc_avenue#2]
The plugin is not supports null safe. is there any way i could use this in my null safe project. Any suggestion would be greatful

**Comment by jaypal1046** [comment]
I would like to work on this issue

**Comment by karthik-reddy-8** [comment]
We started working on this. Sorry for the delay.

Stay tuned for further update in next 3 days.

**Comment by jaypal1046** [comment]
I have migrated the ccavenue plugin to null safety. Im ready to share the
code with you but I would like to be mentioned as a contributor on the
official page.

**Comment by Konda-Koushik** [comment]
@jaypal1046  do you have access to the cc Avenue payment gateway?
We want to make the plugin support for IOS

**Comment by avinash-gotluru** [comment]
@mhdJasir  We are working on it...

**Comment by pankajp12311** [comment]
can you please tell me that how we can handle success payment

**Comment by avinash-gotluru** [comment]
Do you mean the callback ?
