### ISSUE TITLE
Ios Support

### ISSUE THREAD

**Issue by chitraarasu-kirshi** [avinash-gotluru/cc_avenue#4]
Package not working on IOS

**Comment by avinash-gotluru** [comment]
@chitraarasu-kirshi  If have the latest SDK with you please share it with us, so that we can work on it.

**Comment by chitraarasu-kirshi** [comment]
Please contact ccavenue help center they will help you I don't have latest package.

**Comment by avinash-gotluru** [comment]
@chitraarasu-kirshi if anyone can help with sdk then we can update the package. And we don't have access to the CCAvenue. Because we have to pay them periodically. I hope you know about it.

**Comment by chitraarasu-kirshi** [comment]
yeah, ok
