### ISSUE TITLE
Any plans for Flutter Web?

### ISSUE THREAD

**Issue by saurabhsharma2u** [avinash-gotluru/cc_avenue#5]
First of all thank you for this package.

The package has been well-received by developers and has made the integration of ccavenue payment gateway much easier and efficient. Your dedication and hard work have paid off, and it is a great example of the power of open-source software.

However i and other developer struggling to implement same in Flutter Web. Are there any plans for Flutter Web?

**Comment by avinash-gotluru** [comment]
@saurabhsharma2u Definitely we can start enabling the web support. Would you like to join us?

**Comment by saurabhsharma2u** [comment]
@avinash-gotluru 
I am excited to hear about the plans to enable web support for the ccavenue flutter package. Your dedication to continuously improving and expanding the package is truly inspiring.

I would be honored to join the effort and contribute my skills to the project. I have experience in developing for web platforms and I am confident that I can bring value to the team.

Please let me know what steps I need to take to get started. I am eager to begin working with you and the rest of the team to bring the ccavenue flutter package to web platforms.

**Comment by avinash-gotluru** [comment]
@saurabhsharma2u  do we have the ccavenue partner account with you?

**Comment by saurabhsharma2u** [comment]
Yes i have ccavenue partner account for my e-commerce project.

**Comment by avinash-gotluru** [comment]
@saurabhsharma2u Can you please let me know your email?

**Comment by avinash-gotluru** [comment]
@saurabhsharma2u  we are waiting for your response. incase if you want to reach us drop a mail to avinash.gotluru@gmail.com

**Comment by NikeshNayak** [comment]
@avinash-gotluru 
Does your package has support for iOS ?

we need to integrate your package in our app. We need support for both Android & iOS

**Comment by avinash-gotluru** [comment]
@NikeshNayak  we don't have the latest sdk for ccAvenue. if you help them we can work together.
