### ISSUE TITLE
AAPT: error: resource android:attr/lStar not found. 

### ISSUE THREAD

**Issue by sanjeev08-dev** [avinash-gotluru/cc_avenue#6]
cc_avenue\intermediates\merged_res\release\values\values.xml:2525: AAPT: error: resource android:attr/lStar not found.

**Comment by avinash-gotluru** [comment]
@sanjeev08-dev  Could you please elaborate on the issue by sharing the logs?

**Comment by sanjeev08-dev** [comment]
I am getting this issue when try to build release apk of flutter
application

**Comment by avinash-gotluru** [comment]
Please share us the logs and stack trace here ..

**Comment by avinash-gotluru** [comment]
![Screenshot 2023-02-06 at 10 02 33 PM](https://user-images.githubusercontent.com/83296096/217029100-498f9610-979e-4906-87ab-130e691af881.png)

I'm able to generate the APK of flutter. before you build APK please run `flutter clean`.
