### ISSUE TITLE
No IOS Support

### ISSUE THREAD

**Issue by NikeshNayak** [avinash-gotluru/cc_avenue#7]
There is no iOS support for this package. Can anyone help me with this ?

**Comment by avinash-gotluru** [comment]
@NikeshNayak we are ready to help you with it. please confirm do you have the latest SDKs with you?

**Comment by sisirkp** [comment]
@avinash-gotluru yes I have the iOS SDK for Non-Seamless integration, same as the current android implementation. How can I share

**Comment by avinash-gotluru** [comment]
Let's work together to fix the issue can I have your email Id?

**Comment by sisirkp** [comment]
hi Avinash

This is my email address. We can discuss on this.
***@***.***

**Comment by Djsmk123** [comment]
Hi @avinash-gotluru , we need your help to add cc-avenue iOS for flutter.

**Comment by avinash-gotluru** [comment]
Sure contact me on ***@***.***

**Comment by Djsmk123** [comment]
@avinash-gotluru Sorry,your email address is not visible

**Comment by avinash-gotluru** [comment]
You can find it in the profile

**Comment by inamhusain** [comment]
package provide iOS support or not?

**Comment by Djsmk123** [comment]
CCAvenue flutter integration in webview Android/iOS Both 
https://github.com/Djsmk123/ccavenue_flutter_example
For implementation 
https://dev.to/djsmk123/flutter-cc-avenue-payment-gateway-integration-ft-php-1nj7

**Comment by avinash-gotluru** [comment]
As of now we are not planning.
