### ISSUE TITLE
android.content.ActivityNotFoundException: Unable to find explicit activity class {<project_id>/com.avinash.gotluru.cc_avenue.Framework.WebViewActivity}; have you declared this activity in your AndroidManifest.xml?

### ISSUE THREAD

**Issue by RoshanGupta256** [avinash-gotluru/cc_avenue#8]
Getting this bug, can anyone suggest me a solution?

**Comment by premjangir34** [comment]
same here

**Comment by bashadev21** [comment]
<activity android:name="com.avinash.gotluru.cc_avenue.CcAvenuePlugin" android:theme="@style/Theme.AppCompat.NoActionBar"/>
       <activity android:name="com.avinash.gotluru.cc_avenue.Framework.StatusActivity" android:theme="@style/Theme.AppCompat.NoActionBar"/>
       <activity android:name="com.avinash.gotluru.cc_avenue.Framework.WebViewActivity" android:theme="@style/Theme.AppCompat.NoActionBar"/>

Add these lines in manifest file below the </activity> tag!
@RoshanGupta256 @Avinash-Royal

**Comment by bashadev21** [comment]
<activity android:name="com.avinash.gotluru.cc_avenue.CcAvenuePlugin" android:theme="@style/Theme.AppCompat.NoActionBar"/>
       <activity android:name="com.avinash.gotluru.cc_avenue.Framework.StatusActivity" android:theme="@style/Theme.AppCompat.NoActionBar"/>
       <activity android:name="com.avinash.gotluru.cc_avenue.Framework.WebViewActivity" android:theme="@style/Theme.AppCompat.NoActionBar"/>

**Comment by bashadev21** [comment]
<activity android:name="com.avinash.gotluru.cc_avenue.CcAvenuePlugin" android:theme="@style/Theme.AppCompat.NoActionBar"/>
       <activity android:name="com.avinash.gotluru.cc_avenue.Framework.StatusActivity" android:theme="@style/Theme.AppCompat.NoActionBar"/>
       <activity android:name="com.avinash.gotluru.cc_avenue.Framework.WebViewActivity" android:theme="@style/Theme.AppCompat.NoActionBar"/>

**Comment by RoshanGupta256** [comment]
@bashadev21 Thank for the solution, now It's working fine!
