### ISSUE TITLE
Merchant Id not found

### ISSUE THREAD

**Issue by A7Aima** [avinash-gotluru/cc_avenue#9]
![123](https://user-images.githubusercontent.com/61746272/229043944-2a34e11a-6869-41a2-b14c-332ea73a8477.jpg)

image showing merchant ID not found 
but I put exactly as what described on Package Plz help

my code is below

  openCCAvenueCheckout({
    required String amount,
    required String orderId,
    String currency = "INR",
    // int timeout
  }) async {
    await CcAvenue.cCAvenueInit(
      transUrl: "https://test.ccavenue.com/transaction/initTrans",
      //'https://test.ccavenue.com/transaction/transaction.do?command=initiateTransaction',
      rsaKeyUrl: 'https://secure.ccavenue.com/transaction/jsp/GetRSA.jsp',
      // 'https://test.ccavenue.com/transaction/getRSAKey?access_code=${Config.ccAvenueAccessCode}&order_id=$orderId',
      accessCode: Config.ccAvenueAccessCode,
      merchantId: Config.ccAvenueMerchantId,
      amount: amount.toString(),
      orderId: orderId,
      currencyType: currency,
      redirectUrl: 'http://122.182.6.216/merchant/ccavResponseHandler.jsp',
      cancelUrl: 'http://122.182.6.216/merchant/ccavResponseHandler.jsp',
    );
  }

**Comment by avinash-gotluru** [comment]
@A7Aima 

It's not the issue from Package, You need to check with the CCAvenue team, what went wrong

**Comment by avinash-gotluru** [comment]
@A7Aima did you check with the test details mentioned in the readme doc? is it working for you?

**Comment by A7Aima** [comment]
Not working for me 
I followed every detail in readme docs


> @A7Aima did you check with the test details mentioned in the readme doc? is it working for you?

No @avinash-gotluru

**Comment by avinash-gotluru** [comment]
@A7Aima  can you please check with test details and let me know whether you are facing any issues with it?

**Comment by avinash-gotluru** [comment]
@A7Aima  can you please check with test details and let me know whether it's working for you

**Comment by kesamani** [comment]
i also facing same issue any one get solution?? 
please guide me if any solution you have.
